name: deploy-book

on:
  push:
    branches:
    - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv

    - name: Install dependencies
      if: steps.pipenv-cache.outputs.cache-hit != 'true'
      run: |
        pipenv lock -r --dev >> requirements.txt
        pip install -r requirements.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build book

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./book/_build/html
